Remove Maps.immutableEnumMap call
For #844.  Guava 11 doesn't have this method, so it throws
NoSuchMethodError on Hadoop clusters.  Changed to
ImmutableMaps.copyOf.